language: cpp
matrix:
  include:
    - compiler: gcc-5
      os: linux
      addons:
        apt:
          packages:
            - libboost-all-dev
    - compiler: gcc-6
      os: linux
      addons:
        apt:
          packages:
            - libboost-all-dev
    - compiler: clang-3.7
      os: linux
      addons:
        apt:
          packages:
            - libboost-all-dev
    - compiler: clang
      os: osx
    - compiler: clang
      osx_image: xcode8
      os: osx
          
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (brew outdated python || brew upgrade python); fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
script:
  - $CXX -v
  - cd libs; ./initLibraries.sh; cd ..
  - make
