language: cpp
matrix:
  include:
    - compiler: gcc-5
      os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
      env: CXX=g++-5
      env: CC=gcc-5
    - compiler: gcc-6
      os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 
            - libboost-all-dev
      env: CXX=g++-6
      env: CC=gcc-6
    - compiler: clang-3.7
      os: linux
      sudo: required
      dist: trusty    
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang-3.7
            - libboost-all-dev
      env: CXX=clang++-3.7
      env: CC=clang++-3.7
    - compiler: clang
      os: osx
      env: CXX=clang++
      env: CC=clang
    - compiler: clang
      osx_image: xcode8
      os: osx
      env: CXX=clang++
      env: CC=clang
          
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (brew outdated python || brew upgrade python); fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
script:
  - cd libs; ./initLibraries.sh; cd ..
  - qmake Tool.pro
  - make
